mastodon:
  mastodon_instance: https://swiss.social
  mastodon_username: ping13
  feed_item_limit: 5
feedbin:
  starfeed: https://feedbin.com/starred/l4ydHXVjUxwJcS8pypZ0dg.xml
github:
  starfeed: https://api.github.com/users/ping13/starred
