on:
  schedule:
    - cron: '0 * * * *'  # Runs at minute 0 of every hour      
  workflow_dispatch:

name: 🚀 Publish my stars
jobs:
  rss-deploy:
    name: 🎉 Deploy RSS feed
    runs-on: ubuntu-latest
    environment: default
    steps:
    - name: Enable Debug Logging
      run: echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV
      
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"
        
    - name: Install the project
      run: uv sync --no-dev

    - name: Build RSS file
      run: mkdir mastodon && uv run --no-dev rss.py --limit 200 > mastodon/stars.rss
      env:
        MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
        
    - name: 📂 Copy RSS 
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ vars.FTP_SERVER }}
        username: ${{ vars.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./mastodon/
        server-dir: public_html/ping13.net/mastodon/
        

